version: 2
updates:
  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    labels:
      - type:chore
      - area:backend
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    labels:
      - type:chore
      - area:frontend
    open-pull-requests-limit: 5

  - package-ecosystem: terraform
    directory: /infra/environments/dev
    schedule:
      interval: weekly
    cooldown:
      default-days: 5
    labels:
      - type:chore
      - area:infra
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 5
    labels:
      - type:chore
      - area:ci
    open-pull-requests-limit: 5
